### ISSUE TITLE
Does not work when a file is read in setup.py

### ISSUE THREAD

**Issue by lhupfeldt** [gvalkov/setuptools-py2cfg#12]
Package [file_groups](https://github.com/lhupfeldt/file_groups.git)

```
file_groups]$ setuptools-py2cfg
Traceback (most recent call last):
  File "/home/xxx/.local/bin/setuptools-py2cfg", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.9/site-packages/setuptools_py2cfg.py", line 60, in main
    setup, setuppy_dir = execsetup(Path(args.setup_py.name).resolve())
  File "/home/xxx/.local/lib/python3.9/site-packages/setuptools_py2cfg.py", line 51, in execsetup
    exec(setup_py.read_text())
  File "<string>", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/.local/lib/python3.9/site-packages/README.rst'
```

**Comment by amrsoll** [comment]
This is the faulty line:
```python
exec(setup_py.read_text())
```

And the reason is that the interpretor is not running in a separate file, but it's running a string it has been given.

(dunder) variables such as `__file__` or `__name__` etc... will not be proper compared to importing the file (thus running it).

I will try to come up with a solution.
